### ISSUE TITLE
Programming instrutions are wrong (?)

### ISSUE THREAD

**Issue by christakahashi** [xyphro/UsbGpib#14]
I found a second issue so I've edited this to combine them since I think they're probably only worth one commit anyway.
1) The atmega32u4 doesn't have any fuse bits in the upper nibble of the extended fuse byte.  the directions say to use -Uefuse:w:0xcb:m , but I think it should be 0xFB.  AFAIK setting unimplemented fuses just gets ignored but it may cause a failure to verify later as it gets read back 0xFB.

2)  "LED blinking: The USBGPIB converter is connected to a measurement instrument, it is powered off or its GPIB port is disabled. "  should read: "LED blinking: The USBGPIB converter is **not** connected to a measurement instrument, it is powered off or its GPIB port is disabled. "

**Comment by Xyp** [comment]
Thanks a lot for reporting Chris! I will fix it the next days.
