### ISSUE TITLE
Not a issue... Just a question...

### ISSUE THREAD

**Issue by DaviVolcan** [xyphro/UsbGpib#2]
Is this device capable to control multiple instruments? Like an gpib multimeter and a power supply? Using proper gpib cables...
Thanks!

**Comment by Xyp** [comment]
Hi!
As GPIB cables to interconnect instruments are more expensive than building a single one of these adapters + I wanted the concept of a device behaving like a normal USBTMC device, I made the firmware, such that only a single gpib devices is supported. However: Hardware wise it possible to support multiple devices, but a very minor firmware extension to support multiple devices would be required. 
Best regards, 

Kai
