### ISSUE TITLE
Enclosure 3D file formats

### ISSUE THREAD

**Issue by dazz100** [xyphro/UsbGpib#24]
Hi
I'd like to modify the 3D enclosure but I don't use Autocad Fusion360.
I could design a whole new enclosure, but I would prefer to start with your design.

The issue is my CAD program (Designspark Mechanical) can import the following file formats (in order of preference):
OBJ  .obj
Sketchup  .scp
STEP  (read only) .stp
STL   .stl

Could you please upload the 3D model in one of these file formats?
Thanks

**Comment by xyphro** [comment]
Looking at the EEVBlog thread you don't require this anymore it seems, right?
