### ISSUE TITLE
//FIXME: ZLP not OK!

### ISSUE THREAD

**Issue by dazz100** [xyphro/UsbGpib#28]
Hi
I have been looking through your code and noted the comment: 

`//TODO: short packet handling not OK!!!!! Commit an empty packet `

What are the consequences/symptoms of this issue?
Is this something you plan to fix?

**Comment by xyphro** [comment]
I had put a fix there but not removed the comment

dazz100 ***@***.***> schrieb am So., 11. Juni 2023, 12:55:
