### ISSUE TITLE
GND pour on bottom layer in Kicad design

### ISSUE THREAD

**Issue by hobbymachinist** [xyphro/UsbGpib#29]
More a question than an issue, is there a reason there's no ground pour on the bottom layer ? Wanted to check first before I try adding one and then check for loops.

Thanks!

**Comment by xyphro** [comment]
Hi!

I am on vacation in Japan and don't have access to any PC right now, so
cannot check myself. The Kicad design was provided by another user. I my
eagle design you will find gnd pouring on both sides.

If I'll be home, I'd now quickly add GND pouring, but this will still take
some time.

Best regards,

Kai

hobbymachinist ***@***.***> schrieb am Sa., 24. Juni 2023,
10:29:

**Comment by hobbymachinist** [comment]
no worries, it's not urgent. have a good vacation :)

**Comment by xyphro** [comment]
BTW @hobbymachinist: Have changed the Kicad file and applied the gnd pouring on both sides.
However: There will be a new Kicad version coming soon (in about 2 weeks) after testing of the design here.

Will close the issue.
