### ISSUE TITLE
Norcomp step file for 112-024-113R001

### ISSUE THREAD

**Issue by hobbymachinist** [xyphro/UsbGpib#30]
[112-024-113R001.zip](https://github.com/xyphro/UsbGpib/files/11854155/112-024-113R001.zip)

Here's a wip step file for the gpib connector part from Norcomp (with some added colours)

![Screenshot at 2023-06-24 11-45-08](https://github.com/xyphro/UsbGpib/assets/97783830/ba9b3f49-4d8a-43f5-84ae-0695e9039974)

**Comment by xyphro** [comment]
Thanks for sharing!
