### ISSUE TITLE
Selling Extra Boards

### ISSUE THREAD

**Issue by Spegs21** [xyphro/UsbGpib#33]
@xyphro I see you are using the MIT license but I wanted to check with you to see if you'd mind if I sold my extra boards? I fully populated and tested 5 boards, only need one myself. I was thinking about going through Tindie to try and recoup the cost, directing full credit here.

**Comment by xyphro** [comment]
No issue selling leftover boards, but if a commercial product is made, check with me by mail: xyphro@gmail.com.
