### ISSUE TITLE
Dos not apear as usb

### ISSUE THREAD

**Issue by yngve-hansen** [xyphro/UsbGpib#43]
After setting fuses i cant get it to show up. Guess something went wrong but cant understand what.
![image](https://github.com/xyphro/UsbGpib/assets/6376257/723b2c64-2e08-4805-b57d-ae0db311f7af)

**Comment by xyphro** [comment]
Os ot possible that you already have the .bin file programmed too?
Maybe before you had set the fuses?

If so: it is expected defined behavior. It only appears on usb side when it is connected to an instrument and the instrument is powered up.

**Comment by yngve-hansen** [comment]
Not so lucky, it dos not show up.

**Comment by xyphro** [comment]
> Not so lucky, it dos not show up.
> 


Can you explain a bit more?
Did it show up before?

What were your exact stepy?

**Comment by yngve-hansen** [comment]
This is a new module, just initiuliced it and one more.
Same problem on bouth, Crystal is 16mhz.

**Comment by xyphro** [comment]
> This is a new module, just initiuliced it and one more.
> Same problem on bouth, Crystal is 16mhz.
> still responsive on isp.

Do you use the board design I shared or is it some arduino module or so?

**Comment by yngve-hansen** [comment]
It is your design nr w588420as1f1.

**Comment by yngve-hansen** [comment]
I have 5 boards, orderd new. Same fault on the 2 first, will trye a 3 now, but dos not have high hopes.


![IMG_20231027_184931](https://github.com/xyphro/UsbGpib/assets/6376257/72ed0104-5143-49e5-b7d8-f3242b3f2671)
![IMG_20231027_184920](https://github.com/xyphro/UsbGpib/assets/6376257/d9d0df9a-b2a1-4906-b9d3-3b908feb2ade)

**Comment by xyphro** [comment]
w588420as1f1 is a number your PCB production company has added. JLCPCB does this for example.
You used the Kicad project files, which is a user contributed design. But it was reported to work.

The picture seems a bit blurry, C1 looks a bit misplaced. This will likely not be the reason.
Did you solder the IC with paste? So is the Thermal pad (=exposed die pad) connected?
Are the resistors R2 and R3 22 Ohm in value (maybe better measure it once with a multimeter (with USB cable disconnected)?
Does your PC detect the USB device in any way? If you use windows: Does it make any sound when you connect it?

Can you also check once if the XTAL oscillates really on 16 MHz when you connect it to USB? by probing with a scope? Not that it is a harmonic type or so.
You can measure it here (ensure to also have GND connected. You can also connect the aligator clip to the GPIB connector screws or so (better would be close to XTAL).
![grafik](https://github.com/xyphro/UsbGpib/assets/4944408/e94c50ef-6ae2-435a-b645-6d072100bd70)

Fuses are a NIGHTMARE on the AVR controllers. Each programming tool has again a different definition (inverted / non inverted). Atmel should have defined a scheme where the fuses are part of the .HEX file... However, I just crosschecked the fuses again that you used and they are correct.

You can also try to flash this .hex file to see if it changes something: This is an image, where the bootloader and the UsbGpib application are combined in a single image. Note: This one will really only be visible to the PC when you really have it connected to a GPIB instrument and the GPIB instrument is powered on.
[GpibUsbCombined.zip](https://github.com/xyphro/UsbGpib/files/13192901/GpibUsbCombined.zip)

**Comment by yngve-hansen** [comment]
r2 and r3 is 22 ohm, the crystal works(sinus) not tested frekvens.
Smd is solderd by JLCPCB connectors by me.
Windows dos not registrate it in any way.
Found the first problem, it is one command for the fuses and one for boot. They must be run seperatly.
Now it apear in System but missing driver. Will continue to morrow.

**Comment by xyphro** [comment]
Install a visa like R&S visa:
https://www.rohde-schwarz.com/de/applikationen/r-s-visa-application-note_56280-148812.html

This one includes usbtmc driver.

**Comment by xyphro** [comment]
Hvis den vises som en stasjon, betyr det at selve GPIB-applikasjonen fortsatt må blinke.  Hvordan det fungerer er beskrevet i readme.md.  Bare skriv inn copy testandmeasurement.bin F:\flash.bin på kommandolinjen.  F-stasjonen må åpenbart byttes ut med det GPIB-adapteren har.

**Comment by yngve-hansen** [comment]
Mulig den ikke fult ut registrerer hp 54201a, registrerer vertfall ikke fluke 45 i det heletatt.
I enhetsbehandling dukker hp 5421a opp når det slås på.
![image](https://github.com/xyphro/UsbGpib/assets/6376257/b2c15f25-1fdb-4d9d-9baa-2559fcf2044a)
![image](https://github.com/xyphro/UsbGpib/assets/6376257/79d47f4b-9798-4173-bb7b-f3e2043805ed)

**Comment by xyphro** [comment]
Hei Yngve, det ser veldig bra ut. Det er normalt at USBTMC-enheter ikke vises etter navn i enhetsbehandlingen.
Men hvis du søker etter enheter i R&S Visa med testerapplikasjonen, vil de bli oppført der.

Alternativt kan du vise USBTMC-enheter med python og Pyvisa:

`import pyvisa
rm = pyvisa.ResourceManager()
print(rm.list_resources())
`
hvis en feil vises når du kaller import pyvisa-linjen, må pyvisa-pakken fortsatt installeres av:
`pip install pyvisa` samtaler

**Comment by xyphro** [comment]
Her er et eksempel på hvordan det ser ut i enhetsbehandlingen min:
![grafik](https://github.com/xyphro/UsbGpib/assets/4944408/0f1e1679-edb5-429c-a300-af0b7913b94b)

i NI-MAX vises den som en usbtmc-ressurs (jeg kan ikke bruke R&S Visa akkurat nå)
![grafik](https://github.com/xyphro/UsbGpib/assets/4944408/a32f630f-fd1e-4375-8028-83bf576e78f4)

Og i Python ser det slik ut:
![grafik](https://github.com/xyphro/UsbGpib/assets/4944408/65a280e3-5416-4d6b-86ad-a10f3ffd12b6)

**Comment by yngve-hansen** [comment]
Finner ikke drivere til mine instrumenter, mulig det er årsaken til at den ikke dukker opp i  filutforsker.
En annen mulighet er at det har med win11, men kan ikke bruke mere tid på dette nå.
Takker for support selv om det ble resultatløst.
