### ISSUE TITLE
V2 HW JLCPCB issue

### ISSUE THREAD

**Issue by mankangustafsson** [xyphro/UsbGpib#51]
Hi, this is more of an FYI.

Dec 20, 2023 I ordered 5 2*7 panels from JLCPCB of the then just released V2 HW, using the Github gerber files.
Today I soldered the first one and failed to program it. GND and VCC are shorted, maybe I made a short on the USB connector. No, the switch is also shorted, i.e. GND and MOSI which I then found the reason for: The programming pads are too large and have shorted the nearby traces, see attached pictures. 

I've filed a complaint with JLCPCB for the first time but meanwhile I wonder if there are any special instructions necessary for these gerbes to be properly made?

Best regards
Marcus
![2024_0111_190345_001](https://github.com/xyphro/UsbGpib/assets/63975299/1e35aa8a-4381-406e-956b-c810b9367103)
![2024_0111_190358_005](https://github.com/xyphro/UsbGpib/assets/63975299/4d9eb71c-ad94-4201-9aaf-2064a7bafc14)
![2024_0111_190720_001](https://github.com/xyphro/UsbGpib/assets/63975299/9000a55a-15c7-4dca-ad7d-47881014444e)

**Comment by xyphro** [comment]
Hi Marcus,

Never seen this happening, but they clearly modified the Gerber content from what is in there. I mean others already built it without this effect.

No, there are no special instructions required. I ordered it just by dumping the Gerbers in the system - that's it.

Best regards,

Kai

**Comment by xyphro** [comment]
I only see now that they even removed the bottom side pads. Curious to hear their explanation once you got it.

I made in total 4 production runs without issues of that design so far. The last 2 runs were also as panel with v scoring, however, they milled out parially the corner sections.

**Comment by xyphro** [comment]
![20231121_093746.jpg](https://github.com/xyphro/UsbGpib/assets/4944408/2761e221-7dd2-4577-b08e-d57c1af01591)

See here for explanation

**Comment by xyphro** [comment]
Hi Again, Marcus... To entertain my curiosity I made an overlay of the PCB you received to the actual Gerber files that you refer too:
![grafik](https://github.com/xyphro/UsbGpib/assets/4944408/61b313c7-4a18-4022-92e6-ce16cd36c55b)

They did not increase the pad size, but shift the 3 pads - so they clearly modified the files.

**Comment by mankangustafsson** [comment]
Thanks for the overlay, it might come in handy.

I downloaded the productions files and they clearly did the error when making the panels, see below.
/Marcus
![panel_bl](https://github.com/xyphro/UsbGpib/assets/63975299/9135e496-d381-4559-a777-3842f35ef85c)
![panel_tl](https://github.com/xyphro/UsbGpib/assets/63975299/d341cc9b-fc65-44bb-a882-436445acde6d)

**Comment by xyphro** [comment]
Damn, that's frustrating. So next time better: self panelization. Which can be complex, despite the availability of scripts for it.

**Comment by xyphro** [comment]
Hi Marcus,

if you don't mind, I will close this, as this is no UsbGpib design issue, but a vendor specific production issue.

Best regards,

Kai

**Comment by mankangustafsson** [comment]
No problem at all. I have provided more information and pictures to JLC and I am convinced they will solve this. I will still update this issue about the final result

**Comment by mankangustafsson** [comment]
After a few days of back and forth JLCPCB admitted that it all was their fault. They offered a coupon (8USD) for the PCBs while I wanted new PCBs shipped. I settled for one instead of five panels and cheap shipping. Yesterday the boards showed up with DHL Express and five panels in the package. I've now two V2 units up and running.

**Comment by xyphro** [comment]
Perfect, so it was a stressful way with a happy ending. Thanks for sharing your experience!
