### ISSUE TITLE
V2 HW BOM schema discprepancy

### ISSUE THREAD

**Issue by mankangustafsson** [xyphro/UsbGpib#52]
Schema says R7 5.1k, BOM files says 10k. Which should it be? I assume this affects power usage signalling.
Best regards
Marcus

**Comment by xyphro** [comment]
Hi Marcus,

Well spotted, will adjust it.
Good thing is that it will not affect functionality as this will not end up in a too low current beeing delivered to the port.

So I don't see a need to change the resistorvalue in case you mounted it already.

Best regards,

Kai

**Comment by xyphro** [comment]
Hi Marcus,

I adjusted the BOM/CPL file, thanks for sharing - will push the updates in a few minutes!

Best regards,

Kai
