### ISSUE TITLE
Changing settings.

### ISSUE THREAD

**Issue by mariusCZ** [xyphro/UsbGpib#56]
Hi, how would I change the settings of the adapter? Pyvisa library has no method for control_in so can't switch the adapter to receive commands. PyUSB has a control_transfer method, however, writing with PyUSB requires specifying and endpoint then. Could you please elaborate with what you change the settings? Thanks!

**Comment by rjordans** [comment]
#55 has a solution using python-usbtmc, that worked fine for me

**Comment by mariusCZ** [comment]
Thanks!
