### ISSUE TITLE
ATMEGA16U4 support

### ISSUE THREAD

**Issue by ra1nb0w** [xyphro/UsbGpib#6]
Hi,
first of all, thank you very much for sharing this project!
Unfortunately, I soldered an atmega16u4 without re-reading the readme :(
I rebuild `TestAndMeasurement` for that micro and flashed it without bootloader since I have only 16KB of flash (with fuses as suggested). The led works correctly but I don't get the usb descriptor Id and the usb is not recognised. I think that the bootloader set those values but I don't know too much about LUFA. Is there a way to use 16u4 without desoldering it?
thank you

**Comment by irbsurf** [comment]
Hi, guess what I did the same except I haven't soldered it yet! Now the correct IC is out of stock! Did you make it work in the end?
Thanks,
Andrew

**Comment by ra1nb0w** [comment]
No. At the end I substituted the IC.

**Comment by Xyp** [comment]
It would be possible to Support atmega16U if the bootloader is removed. So you'd loose Update capability to Users that don't have a programmer/skills.
Well, right now everybody needs to bring these tools with him... If I manage to get time I can make something, right now it is unfortunately just extremly limited :-(
