### ISSUE TITLE
control_in() not implemented in pyvisa-py

### ISSUE THREAD

**Issue by paulwunner** [xyphro/UsbGpib#61]
Hello,

I am using Ubuntu 24.04 which seems to not support NI-VISA at the time. At least I cannot get it to work on my machine.
Usually pyvisa in combination with pyvisa-py works great, but it has not implemented the control_in function, thus I cannot configure the UsbGpib (e.g. the termination char). Is there a way to store a configuration via USB and the Bootloader into EEPROM?

Thanks in advance, otherwise great device!!

**Comment by rjordans** [comment]
There is a workaround for this in #55

**Comment by paulwunner** [comment]
Thanks, somehow slipped my search for a fix.
