### ISSUE TITLE
Sourcing Connectors

### ISSUE THREAD

**Issue by criscrafter** [xyphro/UsbGpib#64]
Hi,
I want to build a few of these adapters but cant seem to find connectors for the V2 variant.
I got the following devices I can/would want to test with it:

HP 6634A Power Supply
HP 6645A Power Supply
HP 6655A Power Supply
Agilent 8164B Lightwave measurement System
Agilent 4395A Network/ Spectrum/ Impedance Analyzer
Agilent 53131A Counter

Greetings, Friedrich.

**Comment by mankangustafsson** [comment]
I've used [these](https://www.aliexpress.com/item/1005005636771892.html), select 24P, Panel Type, Male. 
/Marcus

**Comment by dazz100** [comment]
I have used the same Aliexpress connectors with success.

**Comment by criscrafter** [comment]
Thank you @mankangustafsson! :)
