### ISSUE TITLE
Gerber files for 0603 components

### ISSUE THREAD

**Issue by tomverbeure** [xyphro/UsbGpib#7]
Hi!

Would it be possible to post the gerber files for the 0603 components?

I think the schematic/PCB is an Eagle project, which I don't have.

Thanks!
Tom

**Comment by xyphro** [comment]
Hi Tom,

Good point and thanks for raising! I have just generated the Gerber files and added them to the repository.
You can find them here: https://github.com/xyphro/UsbGpib/tree/master/HW/Gerber%20files%20biggercomponents

Best regards,

Kai
