### ISSUE TITLE
Python VISA support? 

### ISSUE THREAD

**Issue by ami3go** [xyphro/UsbGpib#8]
Hi. Thanks for sharing it. 
Project looks good. I have some suggestion to make it more robust. 
I think add something like ESD protection for pins.

**Comment by ami3go** [comment]
I found that python is actually supported. Great!

**Comment by Xyp** [comment]
The way it is implemented it is independent on with which software you control it, because it hooks up to visa. Python and matlab are my main preference for automating measurement equipment so what you found is fully correct :-)

ESD... Yeah, can be done. The AVR already has protection diodes internally, it all comes down to the targeted model you want to protect it against.

**Comment by ami3go** [comment]
USB protections probably STF202-22T1G or it's kind 
Also when i was thinking to build it myself i saw GPIB bus drivers, like:
SN75ALS160
SN75ALS161
On the  one hand good to have them, on the other probably it is better to keep BOM cheap and use several of devises instead one, if control more then one piece of equipment.

**Comment by Xyp** [comment]
Bus drivers I kept indeed on purpose out for the methothology of 1 usb port 1 GPIB device as stuff is cheap. Bus drivers add cost and secondary level complexity. Not saying they are wrong, but with above mindset not required. 

Usb protection can certainly be added. If somebody does not want it, they can simply leave it away.
Esd protections are only as good as the testing behind it. Adding an untested ESD protection is not enabling to make claims on ESD safety.
Adding a pad for a commonly available choice is not hurting at all. 

Best regards,

Kai

**Comment by ami3go** [comment]
I will order current version. I think i could test one assembly for ESD as I have access to test lab on work. Let see if need additional protection or not.

**Comment by Xyp** [comment]
That would be nice. I can also test agains different models, just in this covid times more effort. Order a few more AVRs to replace after test :-P
