### ISSUE TITLE
Use Atmega32U4RC w/ Internal Oscillator

### ISSUE THREAD

**Issue by jlpoltrack** [xyphro/UsbGpib#9]
Due to chip availability, would it be possible to use an Atmega32U4RC with internal oscillator?  This would simplify the BOM by not requiring the crystal and capacitors.  Downside is that the device is limited to USB Low-Speed when using the internal oscillator (maybe not a big deal for GPIB speeds?).

Looks like LUFA supports it: https://www.fourwalledcubicle.com/files/LUFA/Doc/170418/html/group___group___device___a_v_r8.html#ga6b9f18eb9033bc6c924d017225024b3a

I have some of these MCUs lying around, so could certainly try out a build.

**Comment by xyphro** [comment]
Unfortunately low speed devices officially [1] do not support Bulk transfers.
The USBTMC class is considering this not designed to support low speed.

[1] I know that bulk transfers practically work e.g. under windows , but this is no guarantee. It is better to change USB device class to e.g. HID or similar for best compatibility.
